### ISSUE TITLE
Add gitter link to README (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#11]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

In order to foster a community of developers that encourages helping each other, we started a gitter chat room just for contributors.

Please edit the README.md file in the root directory of the repository to contain a link to our gitter chat room.

The link should be placed just below the top headline. This is the markdown code required to display the link:

````markdown
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

This will look like this:

[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/DAVFoundation/DAV-Contributors)

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs`. If it isn't, someone is already working on it.
- [ ] Comment on this issue, saying you would like to take this issue.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Add the file**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#4`)

**Comment by ankmachine** [comment]
i would like to take this issue

**Comment by TalAter** [comment]
Thank you @ankmachine

Congratulations on your first pull request, and thank you so much for helping out!

I hope this is the first of many contributions to open-source projects 👍
