### ISSUE TITLE
Create bids only from vehicles with status "available"

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#111]
Thanks you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

Mission Control comes with a built in simulation environment which generates and controls simulated vehicles, allowing developers to start developing without investing in costly hardware first.

When a request for a delivery is raised by the user, vehicles will participate in the bidding. Right now bidding is done by all the vehicles, including the ones not `available`. 

#### What you can do

Modify `bids.js` to only create bids from vehicles that have a status of `available`.

## Contributing to Mission Control

- [ ] Make sure no one has commented below that they are starting to work on this already.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Refer to [contributing.md](https://github.com/DAVFoundation/missioncontrol/blob/master/CONTRIBUTING.md) for project setup instructions.
- [ ] Make your changes.
- [ ] Run `npm test` to verify that all the tests pass.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#6`)
- [ ] Get hooked on open source!

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by mym1990** [comment]
@cg-cnu Hi Sreenivas, I would like to pick up this issue.

**Comment by cg-cnu** [comment]
Hey @mym1990 ! Please go ahead 👍 Thanks!

**Comment by koutron** [comment]
hey @mym1990 you still working on this?  wanted to take a crack at it if youre too busy.

**Comment by TalAter** [comment]
@koutron Please go ahead with this one.

@mym1990 let us know if you're still interested in contributing, we can find more opportunities for you to help 👍

**Comment by bicep** [comment]
@koutron and @mym1990 Hey I'd love to take a stab at this-- are the both of you still working on this?

**Comment by srfrnk** [comment]
Hey @koutron - maybe we can let @bicep take this one?
Also please let us know if you'd like to help in any other way.

@bicep Please go ahead and take this - thanks!

**Comment by bicep** [comment]
Hey @srfrnk, I get that bids are each autonomous vehicle offering a price for their service (?). Could you give me a brief overview of what a need and what needs.js does?

**Comment by srfrnk** [comment]
Sure @bicep - you're exactly right - a Need is the "request" that comes from the client application (e.g. an end user that `needs` a drone delivery) - this is then sent to autonomous vehicles who in turn send their `bids` for supplying the `need`. Does that make sense now?
