### ISSUE TITLE
create getLatestMission() method and refactor existing code

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#130]
## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is Mission Control. Mission Control is a service running on the DAV network, and serving as a marketplace connecting DAV users looking to ship packages, with drone owners.

## How you can help

In `/server/controllers/StatusController.js` there is a call to `getLatestMissionId()` followed by `getMission()` 

```
  const latestMissionId = await getLatestMissionId(user_id);
  const latestMission = await getMission(latestMissionId);
```

We need to refactor this into a new function `getLatestMission()` function in `server/store/missions.js` that returns the latest mission object which included the `missionId` as well. 

Note that lower in the file [here](https://github.com/DAVFoundation/missioncontrol/blob/master/server/controllers/StatusController.js#L33) `latestMissionId` is used, make sure you are replacing it as well.

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by tomscott1** [comment]
I'd like to work on this please.

**Comment by TalAter** [comment]
HI @tomscott1,

This one was already tackled by @griffobeid 

My apologies for not updating the labels on it. I hope to see more contributions from you :octocat:
