### ISSUE TITLE
Refactor missionProgress to ease use and remove a dependency

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#133]
## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

### Mission Control

The DAV project you are looking at is Mission Control. Mission Control is a service running on the DAV network, and serving as a marketplace connecting DAV users looking to ship packages, with drone owners.

## How you can help

in `StatusController` we load the `missionProgress` array of objects from `missionProgress.js`, then run `_.find` to find the right object in it.

Refactor `missionProgress.js` so that instead of containing an array it contains an object where the keys are the `status`, and the value are the same object from the existing array. Then you can change the code in `StatusController` to simply get the right object using its key, and remove the dependency on `_.find`

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by privateOmega** [comment]
I am interested in taking up this issue.

**Comment by TalAter** [comment]
Go for it @privateOmega

**Comment by privateOmega** [comment]
While fixing the issue, I noticed usage of async/await without any catch statements to catch the unhandledpromiserejection errors.

**Comment by TalAter** [comment]
@privateOmega 
Can you be more specific about where it is, why it should be changed, and how? 👍
