### ISSUE TITLE
Write a test to validate the values in mission progress status 'travelling_pickup'

### ISSUE THREAD

**Issue by griffobeid** [DAVFoundation/missioncontrol#167]
Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control
The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### The Issue

Mission Control comes with a built in simulation environment which generates and controls simulated vehicles, allowing developers to start developing without investing in costly hardware first.

One part of the simulation environment is the `missionProgress` script. This script assists the vehicle to know its current status and what it should do next. We need to make sure with a test that the `travelling_pickup` status contains what it is supposed to. 

### What you can do

Write a test in a new file called `simulation.missionProgress.spec.js` that tests the output of the `travelling_pickup` status in the `missionProgress` script. The test should make sure `missionProgress['travelling_pickup']` contains a `status`, `nextVehicleStatus`, `nextMissionUpdate`, and `conditionForNextUpdate`. 

### Contributing to Mission Control
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control Github page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git
- [ ] Take a look at the [Contributing setup and guidelines](https://github.com/DAVFoundation/missioncontrol/blob/master/CONTRIBUTING.md)
- [ ] Now, code, code, code.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/missioncontrol) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by TalAter** [comment]
@griffobeid 
How would these tests be helpful in verifying the project. It will require hardcoding of every single state, and every single property in the state in the test, basically just replicating what is already in `missionProgress.js`... in fact, I would go as far as to say it reduces the reliability of the code because you now have to keep everything up to date in two places.

However, there are many other opportunities for other tests in this file (which is where I am guessing you were going with this next)... specifically testing the `conditionForNextUpdate()` of the various states. We can definitely call those with different mission parameters and see when it says the state needs to update, and when it shouldn't.

**Comment by griffobeid** [comment]
@TalAter Gotcha. I'll look into a more useful test for this file.
