### ISSUE TITLE
Get rid of hasStore() calls throughout app

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#169]
Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

When initially building the app, we imagined an option of running it outside of docker (i.e., without a Redis image available) for testing purposes. This isn't really feasible any more.

Still, there are a few instances throughout the app where we are testing for `hasStore()` - https://github.com/DAVFoundation/missioncontrol/search?q=hasstore&type=Code&utf8=%E2%9C%93

`hasStore()` returns false when running outside of an environment with Redis and then the code is supposed to return some default value instead of calling Redis. This hasn't really happened.

Now is the time to say farewell to `hasStore()` and remove all traces of it.

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Code Code Code **
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by psalv** [comment]
May I claim this issue? 

If so I want to ensure my understanding of the issue is correct; the following files, and any traces of them, need to be deleted altogether since they currently only contain hasStore() information: 

server/store/redis.js
server/lib/environment.js
test/specs/lib.environment.spec.js

Is this correct?

**Comment by TalAter** [comment]
We definitely do not want to delete `server/store/redis.js`

You want to change the code to always assume that had `hasStore()` been there, it would have returned true... you can delete the code that would have run had it returned false.

You can delete:
* `server/lib/environment.js`
* `test/specs/lib.environment.spec.js`

**Comment by psalv** [comment]
Ah I misread the issue, glad I asked. I understand now.

**Comment by georgesco94** [comment]
Hello, 
I would like to try this issue if possible. Think it should be done pretty quick.
Thanks

**Comment by TalAter** [comment]
I believe @psalv is already working on this issue.

**Comment by psalv** [comment]
Created pull request #175 for this issue.

**Comment by cg-cnu** [comment]
Thanks for your awesome work @psalv 👍 Please join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors/) to find out about more opportunities to contribute to DAV and opensource 🙂
