### ISSUE TITLE
create JSDoc comments for the function randomDroneModel (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#17]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

When creating a new simulated drone, we need to create a drone with random name, rating and geo location. The functions creating these random drones are located in [/server/simulation/random.js](https://github.com/DAVFoundation/missioncontrol/blob/master/server/simulation/random.js). Currently, some of the functions don't have comments explaining them. We follow the [jsdoc](http://usejsdoc.org/) style of comments and you can look at the functions `randomRating()` and `randomCoords()` for reference. 

Your task for this issue is to create a doc string for the function `randomDroneModel()` located [here](https://github.com/DAVFoundation/missioncontrol/blob/master/server/simulation/random.js)

You need to describe 

 - [ ] what it does and 

 - [ ] what it returns 

## Contributing to Mission Control

 - [ ] Fork the repository from the Mission Control GitHub page.

 - [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git
 
 - [ ]  Add the jsdoc to the requested function ( in this case `randomDroneModel()`)

 - [ ]  Commit all your changes
 
 - [ ] push your local changes back to github with `$ git push -u origin master`

 - [ ]  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/missioncontrol) and create a pull request for your changes.

 - [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#17`)

**Comment by itsthecheat** [comment]
Would love to jump in on this if still needed

**Comment by cg-cnu** [comment]
@itsthecheat Sure thing! Go ahead :+1:

**Comment by TalAter** [comment]
Thanks @itsthecheat .
Please join our [contributors gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) where you can discuss this issue, ask for help, and find more opportunities to get involved with open-source.
