### ISSUE TITLE
Test that randombid parameters are coordinate objects (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#172]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is Mission Control. Mission Control is a service running on the DAV network, and serving as a marketplace connecting DAV users looking to ship packages, with drone owners.

## How you can help

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is `randomBid()` inside `/server/simulation/vehicles.js`. This function receives three coordinates and returns an object describing a bid (composed of price, time to arrive to pickup point, and time to get from pickup to dropoff)

Coordinate objects should follow the below structure.
```
{
  lat : 1.0,
  long : 2.0,
}
```

In the file `test/specs/simulation.vehicles.spec.js`  in `describe('randomBid()')` block test the following conditions:
* Test that `randomBid()` throws an error when called with first parameter that isn't a coordinate object
* Test that `randomBid()` throws an error when called with second parameter that isn't a coordinate object
* Test that `randomBid()` throws an error when called with third parameter that isn't a coordinate object

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Test Test Test!**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by devrana786** [comment]
I would like to do it

**Comment by raphaeltelatim** [comment]
Hey @cg-cnu, i would like to do it ;)

**Comment by raphaeltelatim** [comment]
Just a question, on topic "Make changes in the LICENSE file", would not be "DO NOT Make changes in the LICENSE file"?

I think i don't understand that one.

**Comment by cg-cnu** [comment]
Hey @raphaeltelatim Thanks for your interest. You can go ahead with the issue. 👍 
Regarding the `license` file, I forgot to update it after creating the issue from the blueprint. Sorry for the confusion, its just a checklist for the first-timers to follow. Thanks for pointing out, I will be careful next time 🙂

**Comment by raphaeltelatim** [comment]
Hey @cg-cnu, i think its done.

https://github.com/DAVFoundation/missioncontrol/pull/177

**Comment by ashis0013** [comment]
Hello, @cg-cnu I am looking for my first open source project and I find this to be my opportunity; so, I'd like to do it :)

**Comment by ashis0013** [comment]
Hello, @cg-cnu I am looking for my first open source project and I find this to be my opportunity; so, I'd like to do it :)

**Comment by srfrnk** [comment]
Hi @ashis0013  - i think this issue has been claimed already.
If you'd like to help maybe you can pick another from [here](https://github.com/DAVFoundation/missions/issues).
Many tnanks!

**Comment by cg-cnu** [comment]
Hey @raphaeltelatim Thanks for your contribution to DAV 🙂 Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors/) to find out about more opportunities to contribute to opensource.
