### ISSUE TITLE
Refactor code so that vehicle object returned from redis just has `coords` property and no `long` and `lat` property

### ISSUE THREAD

**Issue by bicep** [DAVFoundation/missioncontrol#173]
`getVehicle` function calls `redis.hgetAllAsync` which returns a vehicle object with the long and lat property. But then in line 42 of server/store/vehicle.js this vehicle object is given the coords property as well. This is confusing and is not DRY at all. This is even more bug prone when you take into account that the vehicle object returned from the `generateRandom` function in drone.js file has long and lat as undefined. 

**We should just standardize the coordinate information of the vehicle object to being in the coords property of the vehicle object. The long and lat properties should be removed.**

## Possible Solution

The coordinate should be represented in redis as coord instead of long and lat.

**Comment by TalAter** [comment]
There does seem to be a lot of confusion there. Good find 👍 
(Note also the `parseVehiclesArray`)

If you feel like diving in and making sure this is working the same way across the board in all places, go ahead... just be very careful, it might be easy to accidentally break some existing functionality.

**Comment by bicep** [comment]
I'm aware that I'll have to tread carefully- pretty sure much of the code is working based on the `lat` and `long` property. 

I don't mind taking this- I'm  just not too familiar with how redis works. Would love to learn though. Am I right to say that this is an issue that involves me changing the redis schema?

**Comment by TalAter** [comment]
No, please don't change the Redis scheme.

What you can do is have a function that parses the redis output to a unified format. I think parseVehiclesArray already does that. Just need to make sure everything uses the same format.

**Comment by srfrnk** [comment]
Thanks for the work @bicep :tada:
