### ISSUE TITLE
Add tests to check drone generateRandom()

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#19]
### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is the function that creates random simulated drones.

The function `generateRandom()` inside `/server/simulation/simulation.drone.spec.js` needs to be tested to make sure it:

- `returns an object containing 'id' which is a string`
- `returns an object containing 'model' which is a string`
- `returns an object containing 'icon' which is a string`
- `returns an object containing 'coords' which is an object`
- `returns an object containing 'rating' which is a float`
- `returns an object containing 'missions_completed' which is an integer`
- `returns an object containing 'missions_completed_7_days' which is an integer`

Edit `test/specs/simulation.drone.spec.js`, adding tests that verify the conditions mentioned above.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#3`)

**Comment by TalAter** [comment]
Hey @matthewfitch23, do you still intend to take on this issue?

**Comment by matthewfitch23** [comment]
Hi Tal, sorry haven’t got round to doing this. No I don’t but hopefully will be able to pick up another issue in a couple of weeks. Cheers

**Comment by TalAter** [comment]
OK, no worries. Feel free to pick up any of the other issues marked up-for-grabs
