### ISSUE TITLE
Update license (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#198]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22good+first+issue%22+user%3ADAVFoundation+).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, boats, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is Mission Control. It is the main component of the DAV network, used to create a DAV network node which connects vehicles, users, services, and infrastructure together.

## How you can help

This project is open sourced under an MIT license, but the `package.json` file accidentally lists the license as `'ISC'`. Change it to `'MIT'`.

### Contributing to Mission Control

- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Code! Code! Code!**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network

**Comment by jonathan-hamilton** [comment]
I would like to do it.

**Comment by TalAter** [comment]
Thank you @jonathan-hamilton 

Please, go ahead 👍

**Comment by juannat95** [comment]
Would like to do it.

**Comment by veroca88** [comment]
Can I try?

**Comment by TalAter** [comment]
@veroca88 - Please, go ahead 👍

**Comment by TalAter** [comment]
Thank you @jonathan-hamilton 

Looks great!

**Comment by TalAter** [comment]
@veroca88 This one has already been solved.

But the good news is that we have many other open issues - https://github.com/search?q=first-timers-only+org%3ADAVFoundation+label%3A%22up-for-grabs%22&state=open&type=Issues
