### ISSUE TITLE
npm test runs through same file twice

### ISSUE THREAD

**Issue by ankmachine** [DAVFoundation/missioncontrol#20]
npm test runs through test/specs/simulation.drone.spec.js twice and skips test/specs/simulation.random.spec.js. 

![issuewithnpmtest2](https://user-images.githubusercontent.com/17567788/29608289-574d7bb2-8811-11e7-94fa-7f4b5f186d2c.jpeg)

**Comment by TalAter** [comment]
Fixed.
Thanks for alerting me to this one. 👍
