### ISSUE TITLE
repository field missing in package.json (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#23]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

Up on doing `npm install` npm throws a warning saying `npm WARN missioncontrol@0.0.1 No repository field`. Basically, a repository  field is missing in the project's package.json file. 

Your task for this issue is to add the repository field in the [package.json](https://github.com/DAVFoundation/missioncontrol/blob/master/package.json) file.
You can find the example of the `respository` tag in in the other repo's (missions) [package.json](https://github.com/DAVFoundation/missions/blob/master/package.json) 

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] **Add the repository field to the package.json**
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Make sure no warning is thrown as `npm WARN missioncontrol@0.0.1 No repository field.` .
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#23`)

Feel free to ask for help if you need guidance on any of the mentioned steps and procedure! 
We will be happy to help! 😄

**Comment by TalAter** [comment]
Thank you @malltshik, and congratulations on your first pull request 🍾 

I hope it is the first of many contributions to open-source.
