### ISSUE TITLE
Generate random ratings for drones (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#3]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues [here](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

When creating a new simulated drone, it needs to have a rating based on its past performance (e.g. 4.9). Currently, the method that creates this rating always returns the same value.

The function `randomRating()` inside `/server/simulation/random.js` needs to be updated to return a random rating for the drone. A rating is a float between 1.0 and 5.0.

Implement the logic of `randomRating()` like so:

````javascript
console.log(
  randomRating()
); // logs something like 4.9 or 3.6 or 4.0
````

To test your function, follow the instructions in *Contributing to Mission Control*, and after you write your code visit `http://localhost:8888/status`.

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `gulp watch:js` to start a [local server](http://localhost:8888/) and watch your local code for changes. The server will restart automatically every time you change the code.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `gulp` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#3`)

**Comment by cg-cnu** [comment]
can I pick this up ?

**Comment by TalAter** [comment]
@cg-cnu You're no first-timer 😃 

I would love to give people who haven't contributed in the past a chance to learn from these issues (as you can imagine, it takes a lot of work and time to document and write these issues).

I would be very appreciative of any other pull requests from you if you see anything else that needs work. I will also be creating some issues for non-first-timers, which I'll be glad to have your help with.

Thank you for the enthusiasm ❤️ I know how fun it is once you get started. I'm the same way myself.

**Comment by cg-cnu** [comment]
@TalAter Ha ha... 😄 I know, I was just thinking the same but couldn't resist myself 😃 I will be around and try to help the first timers to help setup. Thanks 👍

**Comment by TalAter** [comment]
That's the (open-source) spirit! ❤️

**Comment by JamesDimi** [comment]
Hello! Can i try to solve it?
So you just need the function to return a random number between 1.0 and 5.0?

**Comment by cg-cnu** [comment]
Hey @JamesDimi. Yes, that's it. Feel free to work on it.

**Comment by JamesDimi** [comment]
So i created the function and using vscode .run package to run the function it seems to work as expected.
I try to install though gulp and run it but it seems i do something wrong and the server is not starting (its my first time using gulp, even trying to commit).
Could i send you the pull request anyway?

**Comment by TalAter** [comment]
Looks great @JamesDimi! Thank you for the help 👍 

And congrats on your first pull request. I hope it is the first of many.

<img width="613" alt="jamesdimi__james_dimitrakopoulos_" src="https://user-images.githubusercontent.com/926653/29506229-3a6d5f22-8653-11e7-8156-a214990a5878.png">
