### ISSUE TITLE
Create tests for vehicles - getVehicles()

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#36]
### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

As a project that relies on a large community of contributors, it is very important for us to have good test coverage to make sure changes don't break anything.

The file `/server/simulation/vehicle.js` isn't tested at all. Create a file `/test/specs/simulation.vehicles.spec.js` that will test the function `generateRandomVehicles()`

Test that `generateRandomVehicles()` fulfills these conditions:
- receives an integer or undefined as the first argument (vehicleCount)
- returns an array containing as many objects as the integer passed as the first argument (vehicleCount)
- returns an array containing 4 objects if undefined is passed as the first argument (vehicleCount)
- receives an object containing `lat` and `lang` entries as its second argument (coords)
- receives an integer as its third argument (radius)
- returned objects contain id, model, icon, coords, rating, missions_completed, missions_completed_7_days

You can see how this file should be structured based on the other files in the specs directory.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#28`)

**Comment by ZackTaylor** [comment]
@TalAter I see this one was claimed but it's been a while and no updates. Would I be able to take a shot at this?

**Comment by TalAter** [comment]
I've asked @shpyzer who has already done most of the work on this. If he doesn't have the time to finish this one, we'd love the extra help 👍

**Comment by ZackTaylor** [comment]
@TalAter awesome, keep me posted.

**Comment by TalAter** [comment]
@ZackTaylor 
Looks like this one is still available, would you like to take this one on?
