### ISSUE TITLE
Iknow

### ISSUE THREAD

**Issue by kbekkeli** [DAVFoundation/missioncontrol#37]
learning

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cg-cnu** [comment]
@kbekkeli If you want to learn or test out some gihub features. [githubschool](https://github.com/githubschool) will be the ideal place.  Please try to keep these issues related to missioncontrol. Thanks!
