### ISSUE TITLE
Add code of conduct document (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#4]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

To help create an open and welcoming environment, we would like to have a [code of conduct](https://opensource.guide/code-of-conduct/) document as part of this project.

Please add a file called `code_of_conduct.md` to the root of the project. This file should be based on the [Contributor Covenant Code of Conduct](https://contributor-covenant.org/version/1/4/code_of_conduct.md). This document requires an email address in it. Please enter `tal@dav.network`

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Add the file**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#4`)

**Comment by matthewfitch23** [comment]
@TalAter I have just put in a PR for this issue :)

**Comment by sblasa** [comment]
Hello, @talater, I'm interested in working on this issue.

**Comment by TalAter** [comment]
@matthewfitch23, @sblasa - This issue was just fixed by @JibranKalia in #7.

But we still need help adding this code of conduct to our other two projects.

Would you be so kind and help add this code of conduct to:
- [Captain](https://github.com/DAVFoundation/captain) - @matthewfitch23 
- [Missions](https://github.com/DAVFoundation/missions) - @sblasa 

Thank you so much for the help! ❤️ 

By the way:
**Missions** is the client facing side of the marketplace connecting DAV users looking to ship packages, with autonomous vehicles such as drones.

**The Captain** is the logic that runs onboard vehicles, gives commands to the vehicle, negotiates missions, and communicates with the blockchain.

**Comment by TalAter** [comment]
@sblasa Please check out https://github.com/DAVFoundation/missions/issues/3
