### ISSUE TITLE
Create tests for hasStore()

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#46]
### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### The Issue

As a project that relies on a large community of contributors, it is very important for us to have good test coverage to make sure changes don't break anything.

The file `/server/lib/environment.js` isn't tested at all. Create a file `/test/specs/lib.environment.spec.js` that will test the function `hasStore()`

Test that `hasStore()` fulfills these conditions:
- returns false if the DAV_ENV environment variable isn't set to 'simulated'

You might want to write the test so that it tests both conditions. You can get the environment variable in node using: `process.env.DAV_ENV`

You can see how this file should be structured based on the other files in the specs directory.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#28`)

**Comment by Rob-Rychs** [comment]
will have to read a bit more about jest and follow the structure of the other specs but I will try writing this test

**Comment by cg-cnu** [comment]
Sure @Rob-Rychs, give it a go 👍  If you stuck or need any help feel free to post here. We would be happy to help you out 😄

**Comment by TalAter** [comment]
Hey @Rob-Rychs, do you still intend to take on this issue?

**Comment by Rob-Rychs** [comment]
Hi @TalAter, yes I do! thanks for following up

**Comment by Rob-Rychs** [comment]
So just so I know I'm on the right track I want to write an if/else statement where: 
if (DAV_ENV != 'simulated') we expect hasStore().toBeFalsy() 
and then the opposite condition:
else expect hasStore().toBeTruthy()
Is that getting close to the mark? sorry first ever .spec test and not sure
would it be better to do an else if and specifically check that (DAV_ENV = 'simulated')?
Some thoughts and guidance please and thanks

**Comment by TalAter** [comment]
First, a quick note. Since we want to make sure it returns false, I would use `toBe(false)` rather than `toBeFalsy()`. The latter would also work if it returns undefined, 0, etc.

Second, we want to have each of our tests self-contained and just test a single condition. In other words, the tests that asserts that it `returns false if the DAV_ENV environment variable isn't set to 'simulated'`, should not also test what happens when the environment is set to `simulated` (so, no `else`).

Now, regarding the test itself. It's actually an interesting question of what to test here.

One obvious solution might be to `expect(env !== 'simulation' && hasStore === false)` (that's pseudocode). But it feels to me like a more correct solution would be not to test for the environment variable as part of the assertion, and just test the thing we are testing.

In other words, I think this would be more correct:
````javascript
test(`returns false when the DAV_ENV environment variable isn't set to 'simulated'`, () => {
  expect.assertions(1);
  if (process.env.DAV_ENV !== 'simulation') {
    expect(hasStore).toBe(false);
  }
});
````

It's a subtle difference but it seems like a more *correct* one. The assertion just tests what we came here to test... and if in the future we change the environment that tests run in, it shouldn't fail on `returns false when the DAV_ENV environment variable isn't set to 'simulated'` because `hasStore` didn't break - it functioned correctly, it was the test that failed.

What would happen is that we would get an error saying `Expected one assertion to be called but only received zero assertion calls.` This would be a good chance for us to add tests for other environments.

This would also leave it up to us to implement a future test for the environment separately, and not tied into the test for hasStore.

This is just my view of the matter. You can expect `myView.toBeTruthy()`, but not necessarily `myView.toBe(the only truth)` 😉 

P.S. I made a mistake in the task description. `hasStore` is not actually a function but a constant value. so there's no need to invoke it. Leave the description of the test as is, as I will be refactoring it to a function once you are done adding the test.

**Comment by TalAter** [comment]
Hey @Rob-Rychs,

Let me know if you have further questions.

**Comment by TalAter** [comment]
Looks great, @Rob-Rychs!

Thank you, and thank you for bearing with my idiosyncrasies 😄 

Congrats on joining the community, and becoming an open-sourcerer!

**Comment by TalAter** [comment]
@Rob-Rychs I created a follow up issue to refactor `hasStore` to be a function and not a boolean - #70

Do you want to take that one?

**Comment by Rob-Rychs** [comment]
yes please, thanks @TalAter
