### ISSUE TITLE
Update gitter badge

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#48]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

Your task for this issue is...
In the [README.md](https://github.com/DAVFoundation/missioncontrol/blob/master/README.md) file replace the existing gitter button with the new one.
This [![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/DAVFoundation/DAV-Contributors) has to be changed to this [![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)

You need to replace the existing `[![Gitter chat]]....` with 
````markdown
[![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to work on it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#48`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

**Comment by P-WM** [comment]
I'm looking to do my first PR. Can I work on this?

**Comment by cg-cnu** [comment]
Hi @P-WM Sure go ahead. Its yours 👍

**Comment by P-WM** [comment]
Pull Request submitted. Thanks for the time and effort put into making it easy and fun--you've got me interested in and reading the codebase now!

**Comment by cg-cnu** [comment]
@P-WM Happy to hear that :smile: Glad it made you interested in open source.
Thanks for your awesome work :100: Feel free to join our [gitter chat](gitter.im/DAVFoundation/DAV-Contributors). Looking forward to see you contributing more to open source.

**Comment by TalAter** [comment]
Merged.

Thank you for contributing @P-WM!

If you have any questions about the code or the project, please feel free to ask on [gitter](https://gitter.im/DAVFoundation/DAV-Contributors).

👋 @cg-cnu
