### ISSUE TITLE
Add license badge

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#49]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### The Issue

Your task for this issue is...
In the [README.md](https://github.com/DAVFoundation/missioncontrol/blob/master/README.md) file 
add this following line of code `[![license (https://img.shields.io/github/license/DAVFoundation/missioncontrol.svg?style=flat-square)](https://github.com/DAVFoundation/missioncontrol/blob/master/LICENSE)` to display a badge like this [![license](https://img.shields.io/github/license/DAVFoundation/missioncontrol.svg?style=flat-square)](https://github.com/DAVFoundation/missioncontrol/blob/master/LICENSE)

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to work on it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#49`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

**Comment by qwiktrix** [comment]
Hi would it be possible to take this on?

**Comment by cg-cnu** [comment]
Congratulations @qwiktrix on your first open source contribution 🎆
Thank you for the awesome work! 💯  Your issue will be approved and merged by @TalAter in a bit.
We hope this will be the starting of many of your contributions. Feel free to join our [gitter chat](https://gitter.im/DAVFoundation/DAV-Contributors) and share your experience 😄
