### ISSUE TITLE
Add tests to check random drone generator (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#60]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is `generateRandom()` inside [/server/simulation/drone.js](https://github.com/DAVFoundation/missioncontrol/blob/master/server/simulation/drone.js) that creates random simulated drones

Your task is to extend the test spec in [test/specs/simulation.drone.spec.js](https://github.com/DAVFoundation/missioncontrol/blob/master/test/specs/simulation.drone.spec.js) to test the following condition:

- it returns an object containing a model attribute.

Edit `test/specs/simulation.drone.spec.js`, adding a `test` that verifies the above condition.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#27`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

**Comment by ZackTaylor** [comment]
@TalAter Thanks for opening this, Ill take a shot at this.

**Comment by ZackTaylor** [comment]
@TalAter I got the dev environment all set up, but when I run `npm test` 1 test fails:

`getDavIdIconUrl() › returns an absolute URL

    expect(received).toBeTruthy()
    
    Expected value to be truthy, instead received
      false
      
      at Object.test (test/specs/lib.davIdIcon.spec.js:8:5)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
`

I haven't made any changes yet, should this be occurring?

**Comment by cg-cnu** [comment]
Hey @ZackTaylor It could be because of the version mismatch. What version of node you are on. The project depends on the latest version of node which is `v8.5.0`. Can you try bumping up your version and see if that fixes the problem. 🙂

**Comment by ZackTaylor** [comment]
@cg-cnu awesome installed nvm and node `8.5.0` and tests are green now, thanks!

**Comment by ZackTaylor** [comment]
Can I tackle more issues?
