### ISSUE TITLE
Refactor getDavIdIconUrl()

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#61]
- Expand the `getDavIdIconUrl()` function to receive a `davId` argument, and return `https://lorempixel.com/100/100/abstract/?${davId}`
- Further expand that function so that it throws an exception if no `davId` is passed to it.
- Add JSDoc documentation to that function.
- Make sure everywhere we call that function we didn't forget to pass `davId`
- Update the test that calls it to make sure it passes a `davId` to it (can just be a string, no need to require the function that generates random ids there).
- Create an issue for first timers to add a test to verify that it throws an exception when no `davId` is passed.

**Comment by cg-cnu** [comment]
@TalAter Thanks for creating this. Am on it 😄

**Comment by TalAter** [comment]
@cg-cnu Are you still interested in taking this one, or should we open this up to the community?
