### ISSUE TITLE
Refactor hasStore so that it is a function and not a boolean

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#70]
### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### The Issue

Within `/server/lib/environment.js` is a boolean called `hasStore` which contains true or false, based on the availability of Redis in the current environment. It is currently a boolean, but it should be a function that returns a boolean instead.

In other words:

```javascript
const { hasStore } = require('./server/lib/environment.js');

// This is how we use it now:
if ( hasStore )   useRedis();

// This is how we want to use it:
if ( hasStore() ) useRedis();

```

- Convert the definition of hasStore from a boolean to a function.
- Update the test in `/test/specs/lib.environment.spec.js` and any other place where we call `hasStore` to call it as a function.

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#28`)

**Comment by Rob-Rychs** [comment]
I am working on this issue 👨‍💻
