### ISSUE TITLE
Update 'Contributing to Mission Control' 

### ISSUE THREAD

**Issue by Rob-Rychs** [DAVFoundation/missioncontrol#74]
Hey @TalAter @cg-cnu I was wondering if we could update this part... tripped me up on a previous PR and maybe we can avoid any other people making the same mistake... and spare them a `git revert` on their first PR 😖 

Contributing to Mission Control

 Fork the repository from the Mission Control GitHub page.
 Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
 Make sure you have node.js and npm installed on your machine. You can use this guide for help.
 Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
<b>Sometimes running</b> `npm install` <b>will auto-generate changes to certain files like npm-shrinkwrap.json, this is fine for working locally but DO NOT include this changed file in your pull request! Your pull request should only address the open issue.</b>  
 Run `npm test` to run linting checks and all the automated tests and see that they pass.
 Code! code! code!
 Before committing your code, run npm test one last time and make sure no errors (including linting errors) are thrown.
 Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
 Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/missioncontrol) and create a pull request for your changes.
 Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #64)

**Comment by cg-cnu** [comment]
@Rob-Rychs Thanks for the input. That's actually a valid point. 👍  I will update the default gists with the changes.

**Comment by Rob-Rychs** [comment]
Awesome 😄 
As a bit of a follow-up to this, it looks like switching to yarn and yarn.lock as a package manager would stop this issue from popping up again. Seems npm-shrinkwrap uses a non-deterministic algorithm which causes the npm-shrinkwrap.json's lossy behaviour. See this [post](https://stackoverflow.com/questions/40057469/what-is-the-difference-between-yarn-lock-and-npm-shrinkwrap). Do you think it might be wise to switch to yarn as a package manager sometime in the future?

**Comment by TalAter** [comment]
@Rob-Rychs I have been thinking the same thing... we are already using yarn in missions, but had to stick with npm for now because mission control is deployed in a docker container. This docker container comes preinstalled with npm, but not yarn.

If you really want a challenging task, update the dockerfile to support yarn 👍

**Comment by cg-cnu** [comment]
As mentioned in #77 we should mention the node version to use in the project to avoid confusion. :slightly_smiling_face:
