### ISSUE TITLE
Add test to verify randomDavAddress() works correctly

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#82]
## Knowabunga! 🐢🐢🐢🐢

**This issue is tagged *Knowabunga*. It is only open for participants of the Knowabunga/DAV hackathon!**

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is `randomDavAddress()` inside `/server/simulation/random.js`. This function generates random identities for simulated drones.

Please extend the test spec in `test/specs/simulation.random.spec.js` adding a test to the `describe('randomDavAddress()', () => {` block that tests the following condition:

* it returns a string that begins with 0x followed by 40 hexadecimal characters.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

## Contributing to Mission Control

- [ ] Make sure no one has commented below that they are starting to work on this already.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make your changes.
- [ ] Run `npm test` to verify that all the tests pass.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#6`)
- [ ] Get hooked on open source!

**Comment by afmatthh** [comment]
I'll work on this

**Comment by cg-cnu** [comment]
Hey @afmatthh Go ahead. Its yours... 😄

**Comment by TalAter** [comment]
First :octocat:  pull request of the hackathon!

Thank you so much for your help ❤️ !
