### ISSUE TITLE
Add test to verify randomRating() output

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#83]
Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is `randomRating()` inside `/server/simulation/random.js`. This function generates random identities for simulated drones.

Please extend the test spec in `test/specs/simulation.random.spec.js` adding a test that tests the following condition:

* it returns a floating point number between 4.3 and 5.0

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

## Contributing to Mission Control

- [ ] Make sure no one has commented below that they are starting to work on this already.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make your changes.
- [ ] Run `npm test` to verify that all the tests pass.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#6`)
- [ ] Get hooked on open source!

**Comment by sblasa** [comment]
Hi @TalAter , could I work on this issue? 

Thanks,

**Comment by TalAter** [comment]
@sblasa Of course.

**Comment by sblasa** [comment]
@TalAter great! Thanks!

**Comment by TalAter** [comment]
Hi @sblasa 

Are you still interested in doing this, or can I reopen it to others?

**Comment by sblasa** [comment]
Hi @TalAter, sorry, yes still interested, I will get it to you this week and let you know if I'm having issues with it. Thanks for asking me and being patient. :) 👍

**Comment by sblasa** [comment]
Hello @TalAter, I was experiencing this error when I ran my npm test. 
![image](https://user-images.githubusercontent.com/20133223/34922986-fc763bfa-f94b-11e7-952d-d91a30f28d0c.png)

Maybe I missed something? I will try to sync the latest from your repo again and see if I get the same error. Thanks!

**Comment by TalAter** [comment]
I had the same problem with the test and it is now fixed. Please sync with the latest revision from the repo.

**Comment by sblasa** [comment]
@TalAter, thanks, I will try that!
