### ISSUE TITLE
Test the output of randomCoords() 📐

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/missioncontrol#84]
## Knowabunga! 🐢🐢🐢🐢

**This issue is tagged *Knowabunga*. It is only open for participants of the Knowabunga/DAV hackathon!**

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

The specific project you are looking at is Mission Control. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

## How you can help

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is `randomCoords()` inside `/server/simulation/random.js`. This function receives coordinates and an integer representing max radius in meters from those coordinates. It returns a random coordinate that is within that radius (i.e., the distance between the given point and returned point is less than the max radius)

Please extend the test spec in `test/specs/simulation.random.spec.js` adding a test that tests the following condition:

* it returns a coordinate that is no further than given coordinates by given radius

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

## Contributing to Mission Control

- [ ] Make sure no one has commented below that they are starting to work on this already.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make your changes.
- [ ] Run `npm test` to verify that all the tests pass.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#6`)
- [ ] Get hooked on open source!

**Comment by griffobeid** [comment]
I think I found a solution for this. Not really sure if I put those functions in the proper spot though.
